addSbtPlugin("io.get-coursier" %% "sbt-coursier" % "1.0.0")
addSbtPlugin("com.geirsson" %% "sbt-scalafmt" % "1.4.0")
addSbtPlugin("com.dwijnand" %% "sbt-dynver" % "2.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.0")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.10")
