addSbtPlugin("io.get-coursier" %% "sbt-coursier" % "1.0.0-RC12")
addSbtPlugin("com.geirsson" %% "sbt-scalafmt" % "1.3.0")
addSbtPlugin("com.dwijnand" %% "sbt-dynver" % "2.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.0")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0-M1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.3")
